<a href="https://colab.research.google.com/github/U151198/DeepLearning_2020jrn/blob/master/S1_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LOADING, MANIPULATING AND SAVING DATA**

## Ex. 1

In [0]:
'''
1. read image (dog_1.jpg) with PIL and OpenCV
2. do image manipulation : rotate (45 degree) on PIL and horizontal flip in Opencv  
3. Plot and save them on Results folder

ref : 

https://pillow.readthedocs.io/en/3.1.x/reference/Image.html
https://docs.opencv.org/3.4.2/da/d6e/tutorial_py_geometric_transformations.html
https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html

'''


'\n1. read image (dog_1.jpg) with PIL and OpenCV\n2. do image manipulation : rotate (45 degree) on PIL and horizontal flip in Opencv  \n3. Plot and save them on Results folder\n\nref : \n\nhttps://pillow.readthedocs.io/en/3.1.x/reference/Image.html\nhttps://docs.opencv.org/3.4.2/da/d6e/tutorial_py_geometric_transformations.html\nhttps://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html\n\n'

### Sol. 1 

In [0]:
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')
data_path = '/content/drive/My Drive/DeepLearning_2020/S1/Data/'
results_path = '/content/drive/My Drive/DeepLearning_2020/S1/Results/'
# list files in path
!ls '/content/drive/My Drive/DeepLearning_2020/S1/Data/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ls: cannot access '/content/drive/My Drive/DeepLearning_2020/S1/Data/': No such file or directory


In [0]:
from PIL import Image
import cv2
import matplotlib.pyplot as plt

# Task 1
data_path = '/content/drive/My Drive/DeepLearning_2020/S1/Data/'
ImagePIL = Image.open(data_path+'dog_1.jpg')
ImageCV = cv2.imread(data_path+'dog_1.jpg')

plt.imshow(ImagePIL)

FileNotFoundError: ignored

In [0]:
# Task 2
# Rotation of 45 degrees on PIL
ImagePIL=ImagePIL.rotate(45)
plt.imshow(ImagePIL)

In [0]:
# Task 2
# Correcting color and flipping horitzontally with OpenCV
ImageCVP = cv2.flip(ImageCV,1)
final_image = cv2.cvtColor(ImageCVP, cv2.COLOR_BGR2RGB)
plt.imshow(final_image)

In [0]:
# Task 3
cv2.imwrite(results_path+"dog_modified_CVP.jpg",ImageCVP)
ImagePIL.save(results_path+"dog_modified_PIL.jpg")

## Ex. 2

In [0]:
'''
Load students_score.csv data and : 
  1. augment the data values with +5
  2. swap the y with x
  3. plot and save it as a png file with plt.savefig() in Results folder
'''


### Sol. 2

In [0]:
#usage of Pandas to read and load data
import pandas as pd 
import matplotlib.pyplot as plt #  matplotlib for visualization

# Load table from csv file
csvData = pd.read_csv(data_path+'student_scores.csv')
print('Initial Data:\n',csvData.head())

# Task 1 
csvData += 5
print('\nModified Data:\n',csvData.head())

# Task 2 
columns_titles = ["Scores","Hours"]
csvData=csvData.reindex(columns=columns_titles)
print('\nSwapped Data:\n',csvData.head())

# Task 3
figure = plt.scatter(csvData.Hours,csvData.Scores)
plt.show()
plt.savefig(results_path)

Initial Data:
    Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

Modified Data:
    Hours  Scores
0    7.5      26
1   10.1      52
2    8.2      32
3   13.5      80
4    8.5      35

Swapped Data:
    Scores  Hours
0      26    7.5
1      52   10.1
2      32    8.2
3      80   13.5
4      35    8.5


<Figure size 432x288 with 0 Axes>

# **Numpy & Pytorch**

## Ex. 3

In [0]:
'''
  1. Read the cat_dog_large.jpg (using opencv)
  2. make three variables, numpy (default), torch cpu, torch gpu
  3. gradually increase the brightness of the image by 1, 10 times. 
  4. Calculate the time needed to do this operation for each case (numpy, torch cpu, torch gpu)
'''

## Sol. 3

In [0]:
import cv2
import torch
import numpy as np
import time
ImageCV = cv2.imread(data_path+'cat_dog_large.jpg')
plt.imshow(ImageCV)

In [0]:
numpy_image=np.asarray(ImageCV)
#print(numpy_image)
for i in range(0,10):
  numpy_image=numpy_image-1
print(numpy_image)
plt.imshow(numpy_image)

[[[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 ...

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]]


## Open In Colab Badge

Anybody can open a copy of any github-hosted notebook within Colab. To make it easier to give people access to live views of GitHub-hosted notebooks,
colab provides a [shields.io](http://shields.io/)-style badge, which appears as follows:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)

The markdown for the above badge is the following:

```markdown
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
```

The HTML equivalent is:

```HTML
<a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>
```

Remember to replace the notebook URL in this template with the notebook you want to link to.

# **LINEAR REGRESSION**

## Ex. 5

In [0]:
'''
Using student_scores.csv data, try to estimate the
weight parameter (with gradient-descent using linear regression) to predict the score of given the number of studying hours using 

Steps : 
  1. Load the data on drive
  2. Load data using Pandas -> numpy 
  3. Define the forward, loss and gradient calculation
  4. Optimize the parameter w by adjusting weight in term of loss
  5. Compute the squared error of the predicted value and plot the  different results.
'''

## Sol. 5

In [0]:
# Task 1 and 2 
# Load the data on drive
csvData = pd.read_csv(data_path+'student_scores.csv')
print('Initial Data:\n',csvData.head())

# Load data using Pandas -> numpy 
data = csvData.to_numpy()

Initial Data:
    Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30


In [0]:
# Task 2
# forward pass
def forward(x):
    return x * w

# Loss function definition
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

def gradient(x, y):  # d_loss/d_w
    return 2 * x * (x * w - y)

In [0]:
# Initialize w to an arbitrary number
w = 0.75 

# Set learning rate
lr = 0.005

# Number of iterations
nIt = 15

# List to store losses and parameter w during iterations
loss_iteration = []
w_iteration = []
w_iteration.append(w) # Append initial value

# Gradient descent iteration
for epoch in range(nIt):
    # Iterate over every sample
    total_loss = 0
    for x_val, y_val in zip(x_data, y_data):
        grad = gradient(x_val, y_val)
        w = w - lr * grad
        print("\tgrad: ",round(grad, 4), '\t x-y: ', x_val, y_val,' \t w : ',w )
        l = loss(x_val, y_val)
        # Add the sample loss
        total_loss += l
    # Compute average loss for all the samples during current iteration
    avg_loss = total_loss / x_data.shape[0]
    loss_iteration.append(avg_loss)
    w_iteration.append(w)
    print("progress:", epoch, "w=", round(w, 4), "loss=", round(l, 2))


	grad:  -95.625 	 x-y:  2.5 21.0  	 w :  1.228125
	grad:  -415.5129 	 x-y:  5.1 47.0  	 w :  3.3056896874999997
	grad:  -105.0995 	 x-y:  3.2 27.0  	 w :  3.8311870635
	grad:  -721.3935 	 x-y:  8.5 75.0  	 w :  7.43815441012125
	grad:  -27.7652 	 x-y:  3.5 30.0  	 w :  7.576980494881397
	grad:  -25.9036 	 x-y:  1.5 20.0  	 w :  7.706498433746566
	grad:  -314.6439 	 x-y:  9.2 88.0  	 w :  9.279718159423473
	grad:  -98.5771 	 x-y:  5.5 60.0  	 w :  9.772603416197873
	grad:  1.8693 	 x-y:  8.3 81.0  	 w :  9.763256922779156
	grad:  7.3483 	 x-y:  2.7 25.0  	 w :  9.726515493108556
	grad:  -155.6298 	 x-y:  7.7 85.0  	 w :  10.504664457244493
	grad:  -0.2653 	 x-y:  5.9 62.0  	 w :  10.505990759677685
	grad:  56.4926 	 x-y:  4.5 41.0  	 w :  10.223527630842954
	grad:  -54.5316 	 x-y:  3.3 42.0  	 w :  10.496185471844155
	grad:  -11.9992 	 x-y:  1.1 17.0  	 w :  10.55618162763484
	grad:  -18.6897 	 x-y:  8.9 95.0  	 w :  10.649630160385282
	grad:  -16.8796 	 x-y:  2.5 30.0  	 w :  10.734028

NameError: ignored

# **LOGISTIC REGRESSION**

## Ex. 6

In [0]:
'''
Using Height_Weight.csv data, optimize
the weight parameter (with gradient-descent using logistic regression) predicting the gender from the height and weight variables. 

Steps : 
  1. Load the data on drive
  2. Load data using Pandas -> numpy 
  3. Define the forward, loss and gradient calculation
  4. Optimize w by adjusting weight in term of loss
  5. Compute the prediction error of the predicted value and plot the  different results.
'''

## Sol. 6